version: "3.8"
services:
  avail-da-server:
    image: availj/avail-da-server:latest
    environment:
      - ADDR=0.0.0.0
      - PORT=8080
      - AVAIL_RPC=http://localhost:9933
      - AVAIL_SEED
      - AVAIL_APPID=0
    ports:
      - "${PORT:-8080}:${PORT:-8080}"
      - "8080:8080"
      - "433:433"
